# Generated by Django 4.1.2 on 2023-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=115)),
                ('instagram', models.CharField(max_length=115)),
                ('twitter', models.CharField(max_length=115)),
                ('linkedin', models.CharField(max_length=115)),
            ],
        ),
    ]
