# Generated by Django 4.1.2 on 2023-02-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='occupation',
            new_name='name',
        ),
    ]
