# Generated by Django 4.1.2 on 2023-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_occupation_experience_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
