# Generated by Django 4.1.2 on 2023-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_experience_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
